### ISSUE TITLE
`packunused` library for Stack integration

### ISSUE THREAD

**Issue by decentral1se** [haskell-hvr/packunused#27]
I'd like to follow up on https://github.com/commercialhaskell/stack/issues/39 and integrate `packunused` with Stack. I've only had a quick glance over the code but would it make sense to try and split it up into a library/executable so that the stack integration wouldn't need to duplicate code (not sure if that would be the case).

Just wanted to get some advice here. Thanks.

**Comment by hvr** [comment]
I can give refactoring into lib/exe a try

**Comment by lwm** [comment]
Thanks!  :+1:
