### ISSUE TITLE
New hackage release?

### ISSUE THREAD

**Issue by decentral1se** [haskell-hvr/packunused#33]
Just saw this on https://github.com/fpco/stackage/issues/3048.

**Comment by lwm** [comment]
Oh wait, it just needs a new release, I think. 

Current hackage release is blocked on upper bound of < 0.14.

**Comment by lwm** [comment]
Uhhh, or, it's on the latest version but the bounds have been edited on Hackage? 😕 

I'm not quite sure - consider me confused!

**Comment by hvr** [comment]
Well, I don't necessarily sync Hackage revisions back to Git eagerly (but it's trivial to do; I've got a CLI tool for that). However, the main blocker for the next hackage release is #32

**Comment by lwm** [comment]
Ah, I see! I'll work on something for #32. Thanks.
